### ISSUE TITLE
Revert to att version

### ISSUE THREAD

**Issue by JeoloGong** [EyeCantCU/surface-duo-globalify#1]
Hi Trujillo,

Thanks for your contribution. Some hardware cannot work well in my surface duo. Before I send it to repair, I want to revert to ATT version. Could you please public a guideline on how to revert? Thanks a lot.

**Comment by EyeCantCU** [comment]
Hello,

All you need to do is restore the AT&T recovery image in your recovery. You can find it here:

https://support.microsoft.com/en-us/surface-recovery-image

May I know what hardware isn't working for you?

**Comment by JeoloGong** [comment]
I try official guide but when I run "adb sideload surface-recovery-image.zip" but it failed at 47%. By the way, my fingerprint is not working even I cannot find "fingerprint" in setting. I am not sure it is a software issue or a hardware issue.

**Comment by EyeCantCU** [comment]
That is very odd. Would you try running through all the steps in this guide again only when it asks for the global image, use the AT&T one instead? The script should work all the same as it's generic. Any questions?

When you did this the first time you encountered absolutely no errors? The global build also flashed in recovery just fine? This is rather peculiar.

**Comment by JeoloGong** [comment]
No errors when I used this guide to convert AT&T Surface Duo into the global variant. 

Now let me try all the steps in this guide then I will feedback here. Thanks.

**Comment by EyeCantCU** [comment]
Thank you! Let me know how it goes

**Comment by JeoloGong** [comment]
Wow, it works. Thanks a lot!

**Comment by EyeCantCU** [comment]
No problem!

**Comment by EyeCantCU** [comment]
@JeoloGong found the problem. I'll be updating the guide later today
